"""API key issuance/validation for the text-in `/converse` endpoint.

Not a production auth system - keys are stored in a local JSON file with no expiry
or per-key rate limiting. Good enough for authenticating internal load tests and
programmatic access to this demo deployment, not for a multi-tenant public API.
"""

import json
import secrets
import threading
import time
from pathlib import Path

_KEYS_FILE = Path(__file__).resolve().parent.parent / ".api_keys.json"
_lock = threading.Lock()


def _load_from_disk() -> dict:
    if not _KEYS_FILE.exists():
        return {}
    try:
        return json.loads(_KEYS_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        return {}


def _save(keys: dict) -> None:
    _KEYS_FILE.write_text(json.dumps(keys, indent=2))


# is_valid() runs directly in the FastAPI async event loop (not off-threaded) on
# every single API request, so it must not hit disk per call - a blocking file read
# there serializes concurrent requests through the event loop one at a time (this was
# confirmed as the real bottleneck behind ~7-9s response times under 30-concurrent
# load, not TTS/STT as earlier diagnosis assumed). Cached in memory, refreshed only
# when the file's mtime changes (a stat() call is orders of magnitude cheaper than a
# full read+parse) so keys generated by another process - e.g. a CLI script, not just
# this server's own generate_key() - still become visible without paying that cost on
# every single request.
_cache: dict = _load_from_disk()
_cache_mtime: float | None = _KEYS_FILE.stat().st_mtime if _KEYS_FILE.exists() else None


def _refresh_if_changed() -> None:
    global _cache, _cache_mtime
    try:
        mtime = _KEYS_FILE.stat().st_mtime
    except OSError:
        return
    if mtime != _cache_mtime:
        with _lock:
            _cache = _load_from_disk()
            _cache_mtime = mtime


def generate_key(label: str = "") -> str:
    global _cache_mtime
    key = "ntl_" + secrets.token_urlsafe(32)
    with _lock:
        _cache[key] = {"created": time.time(), "label": label}
        _save(dict(_cache))
        _cache_mtime = _KEYS_FILE.stat().st_mtime
    return key


def is_valid(key: str) -> bool:
    if not key:
        return False
    _refresh_if_changed()
    return key in _cache


def revoke_key(key: str) -> bool:
    """Remove a key so is_valid() stops accepting it. Returns whether it existed."""
    global _cache_mtime
    with _lock:
        existed = _cache.pop(key, None) is not None
        if existed:
            _save(dict(_cache))
            _cache_mtime = _KEYS_FILE.stat().st_mtime
    return existed
